# Generated by Django 4.2.6 on 2025-01-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_post_media_alter_user_cover_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="api.hashtag"
            ),
        ),
    ]
